#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "syncthing"
name = "Syncthing"
description.en = "Continuous file synchronization program"
description.fr = "Programme de synchronisation de fichiers en continu"

version = "2.1.2~ynh1"

maintainers = ["txmrl", "yalh76"]

[upstream]
license = "MPL-2.0"
website = "https://syncthing.net"
userdoc = "https://docs.syncthing.net"
code = "https://github.com/syncthing/syncthing"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = true
sso = true

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/syncthing"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]
    [resources.sources.main]
    arm64.url = "https://github.com/syncthing/syncthing/releases/download/v2.1.2/syncthing-linux-arm64-v2.1.2.tar.gz"
    arm64.sha256 = "2fcee9688f37df46337b0b78e7d2badc44549481e29eccaa8cdb1e698d79c8c5"
    amd64.url = "https://github.com/syncthing/syncthing/releases/download/v2.1.2/syncthing-linux-amd64-v2.1.2.tar.gz"
    amd64.sha256 = "0cea24660ac7d8df19f01da979827b5c9463a8a60042e296829293cf80213ee4"
    armhf.url = "https://github.com/syncthing/syncthing/releases/download/v2.1.2/syncthing-linux-arm-v2.1.2.tar.gz"
    armhf.sha256 = "600f7d37f174825df55df619ef3e90a11f13ea4f4a5ca2a506461772ba9865e9"
    i386.url = "https://github.com/syncthing/syncthing/releases/download/v2.1.2/syncthing-linux-386-v2.1.2.tar.gz"
    i386.sha256 = "0a1ccca77bec371c648be3b1f702f28e0b060ddd9c2cca38f5e7f7a7c122c7eb"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.arm64 = "syncthing-linux-arm64-.*.tar.gz"
    autoupdate.asset.amd64 = "syncthing-linux-amd64-.*.tar.gz"
    autoupdate.asset.i386 = "syncthing-linux-386-.*.tar.gz"
    autoupdate.asset.armhf = "syncthing-linux-arm-.*.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 22000
    main.exposed = "TCP"
    gui.default = 8384
