#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "syncthing"
name = "Syncthing"
description.en = "Continuous file synchronization program"
description.fr = "Programme de synchronisation de fichiers en continu"

version = "2.0.13~ynh1"

maintainers = ["txmrl", "yalh76"]

[upstream]
license = "MPL-2.0"
website = "https://syncthing.net"
userdoc = "https://docs.syncthing.net"
code = "https://github.com/syncthing/syncthing"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = true
sso = true

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/syncthing"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]
    [resources.sources.main]
    arm64.url = "https://github.com/syncthing/syncthing/releases/download/v2.0.13/syncthing-linux-arm64-v2.0.13.tar.gz"
    arm64.sha256 = "f62c7e85c081ea43c6e0c8a8bf428fb2f9c1be7f7d504fb214ddd4e1f056c36b"
    amd64.url = "https://github.com/syncthing/syncthing/releases/download/v2.0.13/syncthing-linux-amd64-v2.0.13.tar.gz"
    amd64.sha256 = "55ffe8a5deefc373c95a760ab71c3cbe77da493bb9bf426525d33c2fe22ead88"
    armhf.url = "https://github.com/syncthing/syncthing/releases/download/v2.0.13/syncthing-linux-arm-v2.0.13.tar.gz"
    armhf.sha256 = "0e2bc61796a053d01f7750e0967c5a120dfbbfeef5cca63eeaaee900af71b97b"
    i386.url = "https://github.com/syncthing/syncthing/releases/download/v2.0.13/syncthing-linux-386-v2.0.13.tar.gz"
    i386.sha256 = "b6b01e842a9b9e0e7d9daaf0738234bc4955632f18e8501164faf2195854e493"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.arm64 = "syncthing-linux-arm64-.*.tar.gz"
    autoupdate.asset.amd64 = "syncthing-linux-amd64-.*.tar.gz"
    autoupdate.asset.i386 = "syncthing-linux-386-.*.tar.gz"
    autoupdate.asset.armhf = "syncthing-linux-arm-.*.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 22000
    main.exposed = "TCP"
    gui.default = 8384
