#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "syncthing"
name = "Syncthing"
description.en = "Continuous file synchronization program"
description.fr = "Programme de synchronisation de fichiers en continu"

version = "2.0.14~ynh1"

maintainers = ["txmrl", "yalh76"]

[upstream]
license = "MPL-2.0"
website = "https://syncthing.net"
userdoc = "https://docs.syncthing.net"
code = "https://github.com/syncthing/syncthing"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = true
sso = true

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/syncthing"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]
    [resources.sources.main]
    arm64.url = "https://github.com/syncthing/syncthing/releases/download/v2.0.14/syncthing-linux-arm64-v2.0.14.tar.gz"
    arm64.sha256 = "1825e1e0dd7813c83d2b8eeb6d17683394511056afd655752a0c2fb21f6ec29c"
    amd64.url = "https://github.com/syncthing/syncthing/releases/download/v2.0.14/syncthing-linux-amd64-v2.0.14.tar.gz"
    amd64.sha256 = "3d4ddb286d57ad4619b59948dbe0ba4dbcdb6bca66bbcf6702d178a8637431aa"
    armhf.url = "https://github.com/syncthing/syncthing/releases/download/v2.0.14/syncthing-linux-arm-v2.0.14.tar.gz"
    armhf.sha256 = "29566cb634fe0d0d43346821180e3fad8c94c9292549fce9c5b4d706b562d85f"
    i386.url = "https://github.com/syncthing/syncthing/releases/download/v2.0.14/syncthing-linux-386-v2.0.14.tar.gz"
    i386.sha256 = "80fe4e9b89391ec65cf9894ed1f095a9547a481d0a34ccc3a4df7fdb83b1d0df"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.arm64 = "syncthing-linux-arm64-.*.tar.gz"
    autoupdate.asset.amd64 = "syncthing-linux-amd64-.*.tar.gz"
    autoupdate.asset.i386 = "syncthing-linux-386-.*.tar.gz"
    autoupdate.asset.armhf = "syncthing-linux-arm-.*.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 22000
    main.exposed = "TCP"
    gui.default = 8384
