#sub_path_only rewrite ^__PATH__$ __PATH__/ permanent;
location __PATH__/ {

  proxy_pass        http://127.0.0.1:__PORT_GUI__/;
  proxy_set_header  Host 127.0.0.1;
  
  include proxy_params_with_auth;

  proxy_read_timeout      600s;
  proxy_send_timeout      600s;
}
