#!/bin/bash

# Retrieve arguments
domain=$1
path=$2
# channel: release or devel. will add choise on install
syncChannel=release


# Configurable variables
syncVersion="0.11.5"
syncHome="/home/yunohost.syncthing"
syncUser=debian-syncthing
syncSyncport=22000
syncUIport=8384

sudo yunohost app checkurl $domain$path -a syncthing
if [[ ! $? -eq 0 ]]; then
  echo $domain$path is not available. Please choose another url for Syncthing.
  exit 1
fi

# Remove trailing "/" for next commands
path=${path%/}

# Check port availability
sudo yunohost app checkport $syncUIport
if [[ ! $? -eq 0 ]]; then
  echo Port $syncUIport for Syncthing UI is not available.
  exit 1
fi
sudo yunohost app checkport $syncSyncport
if [[ ! $? -eq 0 ]]; then
  echo Port $syncSyncport is for Syncthing protocol is not available.
  exit 1
fi

# Open port in firewall
sudo yunohost firewall allow TCP $syncSyncport > /dev/null 2>&1

# Create $syncUser user to run syncthing service
sudo useradd -m  -d $syncHome/ -s /bin/bash $syncUser

# Make directories and set rights
sudo mkdir -p $syncHome/{bin,storage}
sudo chown -R $syncUser:$syncUser $syncHome/
sudo find $syncHome/ -type f | while read LINE; do sudo chmod 640 "$LINE" ; done
sudo find $syncHome/ -type d | while read LINE; do sudo chmod 750 "$LINE" ; done

# Download and install syncthing binary
sudo apt-get install curl
curl -s https://syncthing.net/release-key.txt | sudo apt-key add -
echo "deb http://apt.syncthing.net/ syncthing $syncChannel" | sudo tee /etc/apt/sources.list.d/syncthing-$syncChannel.list
sudo apt-get update
sudo apt-get install syncthing

# Install and monitor service
sudo cp ../conf/syncthing /etc/init.d/syncthing
sudo chmod 0755 /etc/init.d/syncthing
sudo update-rc.d syncthing defaults
sudo yunohost service add -l /var/log/syncthing.log syncthing
sudo service syncthing start

# Configure logrotate if present
if [ -d "/etc/logrotate.d" ]; then
  sudo cp ../conf/logrotate.conf /etc/logrotate.d/syncthing
  sudo chmod 0755 /etc/logrotate.d/syncthing
fi

# Configure Nginx and reload
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sed -i "s@PORTTOCHANGE@$syncUIport@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/syncthing.conf
sudo service nginx reload
echo $?
