#!/bin/bash

# Configurable variables
SYNCHOME="/home/yunohost.app/syncthing"
SYNCUSER=debian-syncthing
SYNCPORT=22000
GUIPORT=8384

# Retrieve arguments
domain=$1
path=$2
user=$3
channel=$4

# Check Debian version
if [[ $(cat /etc/debian_version) = "7."* ]]
then
    echo "You need debian Jessie (8.x) to install gogs."
    exit 1
fi

# Check that admin user is an existing account
sudo yunohost user list --json | grep -q "\"username\": \"$admin\"" \
    || (echo "Error: the chosen admin user does not exist" && exit 1)

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a syncthing
if [[ ! $? -eq 0 ]]; then
  echo $domain$path is not available. Please choose another url for Syncthing.
  exit 1
fi

# Remove trailing "/" for next commands
path=${path%/}

# Check port availability
sudo yunohost app checkport $GUIPORT
if [[ ! $? -eq 0 ]]; then
  echo Port $GUIPORT for Syncthing UI is not available.
  exit 1
fi
sudo yunohost app checkport $SYNCPORT
if [[ ! $? -eq 0 ]]; then
  echo Port $SYNCPORT is for Syncthing protocol is not available.
  exit 1
fi

# Open port in firewall
sudo yunohost firewall allow TCP $SYNCPORT > /dev/null 2>&1

# Create $SYNCUSER user to run syncthing service
sudo useradd -m  -d $SYNCHOME/ -s /bin/bash $SYNCUSER

# Make directories and set rights
sudo chown -R $SYNCUSER:$SYNCUSER $SYNCHOME/
sudo find $SYNCHOME/ -type f | while read LINE; do sudo chmod 640 "$LINE" ; done
sudo find $SYNCHOME/ -type d | while read LINE; do sudo chmod 750 "$LINE" ; done

# Download and install syncthing binary
sudo apt-get install curl
## Add the release PGP keys:
curl -s https://syncthing.net/release-key.txt | sudo apt-key add -
## Add the "release" channel to your APT sources:
echo "deb http://apt.syncthing.net/ syncthing $channel" | sudo tee /etc/apt/sources.list.d/syncthing.list
## Update and install syncthing:
sudo apt-get update -qq
sudo apt-get install syncthing -y --force-yes

# Install and monitor service
sed -i '/^\[Service\]$/,/^\[/ s/^Restart=on-failure/Restart=always/' ~/syncthing.service
sudo systemctl daemon-reload
sudo systemctl enable syncthing@$SYNCUSER.service
#~ sudo yunohost service add -l /var/log/syncthing.log syncthing
sudo yunohost service add syncthing
sudo systemctl start syncthing@$SYNCUSER.service

# Configure logrotate if present
if [ -d "/etc/logrotate.d" ]; then
  sudo cp ../conf/logrotate.conf /etc/logrotate.d/syncthing
  sudo chmod 0755 /etc/logrotate.d/syncthing
fi

# Configure Nginx
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sed -i "s@PORTTOCHANGE@$GUIPORT@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/syncthing.conf

# Remove acces to all users
sudo yunohost app removeaccess syncthing

# Reload nginx and update ssowatch
sudo systemctl reload nginx.service
sudo yunohost app ssowatconf

echo $?
