#!/bin/bash

sudo service syncthing-daemon stop
sudo yunohost firewall disallow TCP 22000
sudo yunohost service remove syncthing-daemon
domain=$(sudo yunohost app setting syncthing domain)

sudo rm /etc/nginx/conf.d/$domain.d/syncthing.conf
sudo rm -rf /home/yunohost.syncthing

sudo apt-get remove -y -qq syncthing-daemon

sudo service nginx reload
sudo yunohost app ssowatconf
