#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_print_info "Loading installation settings..."

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get $app domain)

final_path=$(ynh_app_setting_get $app final_path)

sync_home=$(ynh_app_setting_get $app sync_home)
sync_user=$(ynh_app_setting_get $app sync_user)
sync_port=$(ynh_app_setting_get $app sync_port)
gui_port=$(ynh_app_setting_get $app gui_port)

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE FROM ADMIN PANEL
#=================================================

# Remove a service from the admin panel, added by `yunohost service add`
if yunohost service status $app >/dev/null 2>&1
then
	ynh_print_info "Removing $app service"
	yunohost service remove $app
fi

#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_print_info "Stopping and removing the systemd service"

# Remove the dedicated systemd config
ynh_remove_systemd_config

#=================================================
# REMOVE APP MAIN DIR
#=================================================
ynh_print_info "Removing app main directory"

# Remove the app directory securely
ynh_secure_remove "$final_path"

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_print_info "Removing nginx web server configuration"

# Remove the dedicated nginx config
ynh_remove_nginx_config

#=================================================
# CLOSE A PORT
#=================================================

ynh_print_info "Closing port $sync_port"
ynh_exec_warn_less yunohost firewall disallow TCP $sync_port

#=================================================
# GENERIC FINALIZATION
#=================================================
# REMOVE DEDICATED USER
#=================================================
ynh_print_info "Removing the dedicated system user"

# Delete a system user
ynh_system_user_delete $app

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Removal of $app completed"
