#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop" --log_path=systemd

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir" --full_replace --keep=".config/syncthing/config.xml"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

mkdir -p "$install_dir/.config/syncthing"
config_file="$install_dir/.config/syncthing/config.xml"

ynh_config_add --template="config.xml" --destination="$config_file"

chown -R $app: $install_dir

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd

yunohost service add $app --description="Continuous File Synchronization" --needs_exposed_ports=$port

#=================================================
# FIX LISTENING SERVICE
#=================================================
ynh_script_progression "Fixing listening service..."

ynh_systemctl --service=$app --action="start" --log_path=systemd --wait_until="Access the GUI via the following URL"

ynh_replace --match="<listenAddress>tcp://quic:%2F%2F0.0.0.0:$port</listenAddress>" --replace="<listenAddress>quic//0.0.0.0:$port</listenAddress>" --file="$config_file"

ynh_systemctl --service=$app --action="stop" --log_path=systemd

ynh_store_file_checksum "$config_file"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --log_path=systemd --wait_until="Access the GUI via the following URL"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
